version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@athos.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres-db
  postgres-db:
    container_name: postgres-mc
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=inventory-service
    ports:
      - "5432:5432"